# Generated by Django 5.0.1 on 2024-09-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user',
            new_name='extended_user',
        ),
    ]
