# Generated by Django 5.0.1 on 2024-09-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_cartitem_orderitem_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catergory',
            new_name='catergory',
        ),
    ]
